### ISSUE TITLE
SCurve question

### ISSUE THREAD

**Issue by HaogeL** [igorauad/symbol_timing_sync#2]
Hi,

Could you please point me to the reference of Equation 8.30, 8.45, etc. that you used to calculate SCurve for TED.
Thank you!

Best regards,
HG

**Comment by igorauad** [comment]
Hi @HaogeL ,

Thanks for reaching out. Nearly all equations in the code are based on the "Digital Communications: A Discrete-Time Approach" book by Michael Rice. I mention the book in the [README page](https://github.com/igorauad/symbol_timing_sync#overview) and [here](https://github.com/igorauad/symbol_timing_sync/blob/f78a5658c9a5b4c279b47f9b8e68deff09505095/symbolTimingSync.m#L85).

Regards

**Comment by HaogeL** [comment]
Thanks!
